### ISSUE TITLE
How to set socket options ?

### ISSUE THREAD

**Issue by tienhm0202** [fschr/simpletcp#8]
When I `Ctrl+C` to stop server and restart, I got an error:
```
Traceback (most recent call last):
  File "tcp/tcp_main.py", line 32, in <module>
    server = TCPServer(HOST, PORT, handle_tcp_non_blocking, recv_bytes=1024)
  File "/home/ubuntu/giamsat/gs/lib/python3.5/site-packages/simpletcp/tcpserver.py", line 22, in __init__
    mode, port, read_callback, maximum_connections, recv_bytes
  File "/home/ubuntu/giamsat/gs/lib/python3.5/site-packages/simpletcp/serversocket.py", line 32, in __init__
    self._socket.bind((self.ip, self.port))
OSError: [Errno 98] Address already in use
```

So I want to set socket.SO_REUSEADDR to avoid it and I used
```
server = TCPServer(HOST, PORT, handle_tcp_non_blocking, recv_bytes=1024)
server.serversocket._socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server.run()
```
but it's not work. 

So, please tell me how to set socket option to this server.

**Comment by fschr** [comment]
I think this is more of an OS-level issue. SO_REUSEADDR is  very complicated and I'm not sure that your program should work based on the information you posted.

If you can post the full program, I can try to determine if this is actually a `simpletcp` issue, or if it's an OS-level issue out of our control.

[This SO past has a good overview of SO_REUSEADDR](http://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t)

**Comment by tienhm0202** [comment]
This is my full program
```
server = TCPServer(HOST, PORT, echo)
server.serversocket._socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
server.run()
```
But I can't set options `SO_REUSEADDR` for socket because socket is already bind when init SockerServer. So I just wish for a way to set socket options for my `simpletcp`, can I ?

**Comment by fschr** [comment]
As you pointed out, you have to set the socket's options before binding. There is currently no way to do this in `simpletcp`.

You could make a pull request if you think you've found a solution. Otherwise, I'll probably do one myself after this semester (when I'm not so busy).

**Comment by fschr** [comment]
@tienhm0202 thanks for opening this issue, btw :+1:
